### ISSUE TITLE
https://explorer.melroy.org is down

### ISSUE THREAD

**Issue by sandakersmann** [BitcoinCash1/Explorer#1]
https://explorer.melroy.org is down

**Comment by melroy89** [comment]
We are aware of the network connectivity issue. My ISP is already informed, but the network is indeed down. 

Sorry for the inconvenience, hopefully T-Mobile solve the fiberglass connection issue soon again.

**Comment by melroyvandenberg** [comment]
Mechanic is coming today.

**Comment by melroy89** [comment]
It's resolved, not really sure why my provider needed to register the Optical Network Terminal (ONT) again.
